version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1 # Defina a região da AWS
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    #      - "./scripts/setup_bootstrap.sh:/etc/localstack/init/ready.d/setup_bootstrap.sh"
    #      - "./scripts/HookFunction.zip:/opt/code/localstack/HookFunction.zip"
    command: [ "sh", "/etc/localstack/init/ready.d" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"